spring:
  mail:
    host: localhost
    port: 25
    username: ''
    password: ''
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  data:
    mongodb:
      uri: mongodb+srv://electriceye:fJrfMkGGIXoumvHs@lumunix.e4lf5.mongodb.net/fursona?retryWrites=true
